spring.datasource.url=jdbc:postgresql://localhost:5432/paiement
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration des messages d'erreur de validation
spring.messages.basename=validation
spring.messages.encoding=UTF-8

# Configuration du logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuration de l'application
spring.application.name=recrutement-app
server.port=8082

# Configuration des dates
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Europe/Paris
