spring.datasource.url=jdbc:postgresql://localhost:5432/recrutement
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eya.ouchem@etudiant-fst.utm.tn
spring.mail.password=vyin rlmm mdua mdas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Swagger configurationvalid
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.version=1.0.0
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration des messages d'erreur de validation
spring.messages.basename=validation
spring.messages.encoding=UTF-8

# Configuration du logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuration de l'application
spring.application.name=recrutement-app?
server.port=8082

# Configuration des dates
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Europe/Paris
